version: '3'

name: link-slicer
services:
  link-slicer-db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=link-slicer
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=mysqladmin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  link-slicer-server:
    image: link-slicer-server
    build:
      context: .
    environment:
      - APP_NAME=link-slicer
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}

      - DB_CONNECTION=mysql
      - DB_HOST=link-slicer-db
      - DB_PORT=3306
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_USERNAME=mysqladmin
      - DB_DATABASE=link-slicer

      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGO=HS256
    depends_on:
      - link-slicer-db
